### ISSUE TITLE
真机奔溃

### ISSUE THREAD

**Issue by xiaowasly** [easefun/PolyvStreamerDemo#1]
编译可以通过 真机测试就奔溃

dyld: Symbol not found: __TMps13IndexableBase
  Referenced from: /private/var/containers/Bundle/Application/9D275B95-EA78-48C7-8833-A59CFBEEB485/PLVLiveDemo.app/Frameworks/SocketIO.framework/SocketIO
  Expected in: /private/var/containers/Bundle/Application/9D275B95-EA78-48C7-8833-A59CFBEEB485/PLVLiveDemo.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/9D275B95-EA78-48C7-8833-A59CFBEEB485/PLVLiveDemo.app/Frameworks/SocketIO.framework/SocketIO

**Comment by Zeaa** [comment]
@xiaowasly 没有设置`Target -> Build Settings -> Aways Embed Swift Standard Libraries 设置YES` 吧
或者删除工程中的`SoketIO.framework`库，使用cocopod添加[Socket.IO-Client-Swift](https://github.com/socketio/socket.io-client-swift)
```
use_frameworks!

target 'YourApp' do
    pod 'Socket.IO-Client-Swift', '~> 8.3'
end
```
Xcode8.3需要`socketIO` 8.3以上版本
